# 路由规则配置
spring:
  cloud:
    gateway:
      routes:
        - id: server
          uri: lb://tiny-server
          predicates:
            - Path=/v1/employee/**


      httpclient:
        pool:
          maxConnections: 50
          maxIdleTime: PT300S
          maxLifeTime: PT600S
          evictionInterval: PT600S
          type: FIXED


## 服务治理配置
servicecomb:
  matchGroup:
    allOperation: |
      matches:
        - apiPath:
            prefix: "/"
  rateLimiting:
    ## 限流器每10毫秒允许通过100个请求，如果一个请求超过1000毫秒没有获取到
    ## 许可，将被拒绝
    allOperation: |
      rate: 10
      limitRefreshPeriod: 1
      timeoutDuration: 1000
  instanceIsolation:
    ## 熔断器错误率达到50%或者耗时请求达到100%，将开启。
    ## 开启时间为5000毫秒，然后会放通10个请求。
    allOperation: |
      minimumNumberOfCalls: 10
      slidingWindowSize: 100
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5000
      waitDurationInOpenState: 5000
      permittedNumberOfCallsInHalfOpenState: 10
  instanceBulkhead:
    ## 隔离仓限制正在处理的请求数为20个，新来的请求等待1000毫秒没有获取到
    ## 许可，将被拒绝。
    allOperation: |
      maxConcurrentCalls: 50
      maxWaitDuration: 1000

