import get from './get';
import getReallyName from './getReallyName';
import installOne from './install-one';
import localExist from './local-exist';
import localList from './local-list';
import onlineExist from './online-exist';
import onlineList from './online-list';
import update from './update';
declare const _default: {
    get: typeof get;
    getReallyName: typeof getReallyName;
    localExist: typeof localExist;
    onlineExist: typeof onlineExist;
    localList: typeof localList;
    onlineList: typeof onlineList;
    installOne: typeof installOne;
    update: typeof update;
    getEsModule: (fn: any) => any;
    utils: {
        moduleFilter(list: any, type: string): any;
        toolkitPrefix: () => string;
        pluginPrefix: () => string;
        toolkitFullName: (name: string) => string;
        pluginFullName: (name: string) => string;
        fullName: (name: string) => string;
        prefix: () => string;
        UPDATE_CHECK_PRE: string;
        ONLINE_MODULE_CACHE_KEY_IN: string;
        ONLINE_MODULE_CACHE_KEY_OUT: string;
        updateLog: (name: string, opt?: any) => void;
        addModuleToDependencies: (cwd: string, name: string, version: string) => void;
        removeModuleToDependencies: (cwd: string, name: string) => void;
        NO_TIP_PERIOD: number;
    };
};
export default _default;
