export const menuData = [
  {
    name: 'Board',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: 'iconApplication',
    component: 'board/index',
    path: 'board',
  },
  {
    name: 'Home',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'board/home/index',
    path: 'home',
  },
  {
    name: 'Work',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'board/work/index',
    path: 'work',
  },
  {
    name: 'List',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: 'iconFiles',
    component: 'list/index',
    path: 'list',
  },
  {
    name: 'Table',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'list/search-table/index',
    path: 'table',
  },
  {
    name: 'Form',
    order: 3,
    parentId: null,
    menuType: 'normal',
    icon: 'iconSetting',
    component: 'form/index',
    path: 'form',
  },
  {
    name: 'Base',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'form/base/index',
    path: 'base',
  },
  {
    name: 'Step',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'form/step/index',
    path: 'step',
  },
  {
    name: 'Profile',
    order: 4,
    parentId: null,
    menuType: 'normal',
    icon: 'iconFiletext',
    component: 'profile/index',
    path: 'profile',
  },
  {
    name: 'Detail',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'profile/detail/index',
    path: 'detail',
  },
  {
    name: 'Result',
    order: 5,
    parentId: null,
    menuType: 'normal',
    icon: 'iconSuccessful',
    component: 'result/index',
    path: 'result',
  },
  {
    name: 'Success',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'result/success/index',
    path: 'success',
  },
  {
    name: 'Error',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'result/error/index',
    path: 'error',
  },
  {
    name: 'Exception',
    order: 6,
    parentId: null,
    menuType: 'normal',
    icon: 'iconCuel',
    component: 'exception/index',
    path: 'exception',
  },
  {
    name: '403',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'exception/403/index',
    path: '403',
  },
  {
    name: '404',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'exception/404/index',
    path: '404',
  },
  {
    name: '500',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'exception/500/index',
    path: '500',
  },
  {
    name: 'User',
    order: 7,
    parentId: null,
    menuType: 'normal',
    icon: 'iconUser',
    component: 'user/index',
    path: 'user',
  },
  {
    name: 'Info',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'user/info/index',
    path: 'info',
  },
  {
    name: 'Setting',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'user/setting/index',
    path: 'setting',
  },
  {
    name: 'Cloud',
    order: 8,
    parentId: null,
    menuType: 'normal',
    icon: 'iconDownloadCloud',
    component: 'cloud/index',
    path: 'cloud',
  },
  {
    name: 'Hello',
    order: 1,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'cloud/hello/index',
    path: 'hello',
  },
  {
    name: 'Contracts',
    order: 2,
    parentId: null,
    menuType: 'normal',
    icon: '',
    component: 'cloud/contracts/index',
    path: 'contracts',
  },
  {
    name: 'Menu',
    order: 9,
    parentId: null,
    menuType: 'admin',
    icon: 'iconGrade',
    component: 'menu/index',
    path: 'menu',
  },
  {
    name: 'AllMenu',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'menu/info/index',
    path: 'allMenu',
  },
  {
    name: 'Permission',
    order: 10,
    parentId: null,
    menuType: 'admin',
    icon: 'iconFolderOpened',
    component: 'permission/index',
    path: 'permission',
  },
  {
    name: 'AllPermission',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'permission/info/index',
    path: 'allPermission',
  },
  {
    name: 'Role',
    order: 11,
    parentId: null,
    menuType: 'admin',
    icon: 'iconActivation',
    component: 'role/index',
    path: 'role',
  },
  {
    name: 'AllRole',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'role/info/index',
    path: 'allRole',
  },
  {
    name: 'UserManager',
    order: 12,
    parentId: null,
    menuType: 'admin',
    icon: 'iconGroup',
    component: 'userManager/index',
    path: 'userManager',
  },
  {
    name: 'AllInfo',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'userManager/info/index',
    path: 'allInfo',
  },
  {
    name: 'AllSetting',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'userManager/setting/index',
    path: 'allSetting',
  },
  {
    name: 'UserAdd',
    order: 1,
    parentId: null,
    menuType: 'admin',
    icon: '',
    component: 'userManager/useradd/index',
    path: 'userAdd',
  },
]
