/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "common": {
            "unauth": string;
            "tokenError": string;
            "tokenExpire": string;
            "forbidden": string;
        };
        "user": {
            "oldPasswordError": string;
            "userExists": string;
            "userNumberNull": string;
        };
        "role": {
            "exists": string;
            "notExists": string;
            "conflict": string;
        };
        "permission": {
            "exists": string;
            "notExists": string;
        };
        "menu": {
            "exists": string;
            "notExists": string;
        };
        "lang": {
            "notExists": string;
            "exists": string;
            "notExistsCommon": string;
            "DELETE_LANG_CONFLICT": string;
        };
        "i18": {
            "exists": string;
            "notExists": string;
        };
        "auth": {
            "userNotExists": string;
            "passwordOrEmailError": string;
        };
        "preview": {
            "reject-this-request": string;
        };
    };
    "validation": {
        "NOT_EMPTY": string;
        "IS_ARRAY": string;
        "NOT_EMPTY_HUMAN": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
